
import __ASTRO_IMAGE_IMPORT_1NPnb from "~/assets/images/hiking/south-sister-trail.jpg?astroContentImageFlag=&importer=src%2Fdata%2Fpost%2Fsouth-sister-summit.md";
import __ASTRO_IMAGE_IMPORT_Z23jTjm from "~/assets/images/hiking/south-sister-climb.jpg?astroContentImageFlag=&importer=src%2Fdata%2Fpost%2Fsouth-sister-summit.md";
import __ASTRO_IMAGE_IMPORT_mESM0 from "~/assets/images/hiking/south-sister-summit.jpg?astroContentImageFlag=&importer=src%2Fdata%2Fpost%2Fsouth-sister-summit.md";
import __ASTRO_IMAGE_IMPORT_1D27rJ from "~/assets/images/hiking/broken-hand-trailhead.jpg?astroContentImageFlag=&importer=src%2Fdata%2Fpost%2Fbroken-hand-hike.md";
import __ASTRO_IMAGE_IMPORT_Z2gcbMV from "~/assets/images/hiking/broken-hand-ridge.jpg?astroContentImageFlag=&importer=src%2Fdata%2Fpost%2Fbroken-hand-hike.md";
import __ASTRO_IMAGE_IMPORT_ZI4nOi from "~/assets/images/hiking/broken-hand-dogs-trail.jpg?astroContentImageFlag=&importer=src%2Fdata%2Fpost%2Fbroken-hand-hike.md";
import __ASTRO_IMAGE_IMPORT_Z1SrK6U from "~/assets/images/hiking/broken-hand-summit.jpg?astroContentImageFlag=&importer=src%2Fdata%2Fpost%2Fbroken-hand-hike.md";
import __ASTRO_IMAGE_IMPORT_Z1OPYEU from "~/assets/images/hiking/broken-hand-dogs-summit.jpg?astroContentImageFlag=&importer=src%2Fdata%2Fpost%2Fbroken-hand-hike.md";
import __ASTRO_IMAGE_IMPORT_1VxBCe from "~/assets/images/hiking/cabot-lake-trailhead.jpg?astroContentImageFlag=&importer=src%2Fdata%2Fpost%2Fcabot-lake-backpacking.md";
import __ASTRO_IMAGE_IMPORT_2aqvG5 from "~/assets/images/hiking/cabot-lake-trail.jpg?astroContentImageFlag=&importer=src%2Fdata%2Fpost%2Fcabot-lake-backpacking.md";
import __ASTRO_IMAGE_IMPORT_Z1iM04w from "~/assets/images/hiking/cabot-lake-camp.jpg?astroContentImageFlag=&importer=src%2Fdata%2Fpost%2Fcabot-lake-backpacking.md";
import __ASTRO_IMAGE_IMPORT_1hT6E7 from "~/assets/images/hiking/cabot-lake-evening.jpg?astroContentImageFlag=&importer=src%2Fdata%2Fpost%2Fcabot-lake-backpacking.md";
import __ASTRO_IMAGE_IMPORT_Z16lgiz from "~/assets/images/hiking/cabot-lake-storm.jpg?astroContentImageFlag=&importer=src%2Fdata%2Fpost%2Fcabot-lake-backpacking.md";
import __ASTRO_IMAGE_IMPORT_2kDOyR from "~/assets/images/hiking/cabot-lake-morning.jpg?astroContentImageFlag=&importer=src%2Fdata%2Fpost%2Fcabot-lake-backpacking.md";
export default new Map([["~/assets/images/hiking/south-sister-trail.jpg?astroContentImageFlag=&importer=src%2Fdata%2Fpost%2Fsouth-sister-summit.md", __ASTRO_IMAGE_IMPORT_1NPnb], ["~/assets/images/hiking/south-sister-climb.jpg?astroContentImageFlag=&importer=src%2Fdata%2Fpost%2Fsouth-sister-summit.md", __ASTRO_IMAGE_IMPORT_Z23jTjm], ["~/assets/images/hiking/south-sister-summit.jpg?astroContentImageFlag=&importer=src%2Fdata%2Fpost%2Fsouth-sister-summit.md", __ASTRO_IMAGE_IMPORT_mESM0], ["~/assets/images/hiking/broken-hand-trailhead.jpg?astroContentImageFlag=&importer=src%2Fdata%2Fpost%2Fbroken-hand-hike.md", __ASTRO_IMAGE_IMPORT_1D27rJ], ["~/assets/images/hiking/broken-hand-ridge.jpg?astroContentImageFlag=&importer=src%2Fdata%2Fpost%2Fbroken-hand-hike.md", __ASTRO_IMAGE_IMPORT_Z2gcbMV], ["~/assets/images/hiking/broken-hand-dogs-trail.jpg?astroContentImageFlag=&importer=src%2Fdata%2Fpost%2Fbroken-hand-hike.md", __ASTRO_IMAGE_IMPORT_ZI4nOi], ["~/assets/images/hiking/broken-hand-summit.jpg?astroContentImageFlag=&importer=src%2Fdata%2Fpost%2Fbroken-hand-hike.md", __ASTRO_IMAGE_IMPORT_Z1SrK6U], ["~/assets/images/hiking/broken-hand-dogs-summit.jpg?astroContentImageFlag=&importer=src%2Fdata%2Fpost%2Fbroken-hand-hike.md", __ASTRO_IMAGE_IMPORT_Z1OPYEU], ["~/assets/images/hiking/cabot-lake-trailhead.jpg?astroContentImageFlag=&importer=src%2Fdata%2Fpost%2Fcabot-lake-backpacking.md", __ASTRO_IMAGE_IMPORT_1VxBCe], ["~/assets/images/hiking/cabot-lake-trail.jpg?astroContentImageFlag=&importer=src%2Fdata%2Fpost%2Fcabot-lake-backpacking.md", __ASTRO_IMAGE_IMPORT_2aqvG5], ["~/assets/images/hiking/cabot-lake-camp.jpg?astroContentImageFlag=&importer=src%2Fdata%2Fpost%2Fcabot-lake-backpacking.md", __ASTRO_IMAGE_IMPORT_Z1iM04w], ["~/assets/images/hiking/cabot-lake-evening.jpg?astroContentImageFlag=&importer=src%2Fdata%2Fpost%2Fcabot-lake-backpacking.md", __ASTRO_IMAGE_IMPORT_1hT6E7], ["~/assets/images/hiking/cabot-lake-storm.jpg?astroContentImageFlag=&importer=src%2Fdata%2Fpost%2Fcabot-lake-backpacking.md", __ASTRO_IMAGE_IMPORT_Z16lgiz], ["~/assets/images/hiking/cabot-lake-morning.jpg?astroContentImageFlag=&importer=src%2Fdata%2Fpost%2Fcabot-lake-backpacking.md", __ASTRO_IMAGE_IMPORT_2kDOyR]]);
		